import { useState } from "react";
import { useNavigate } from "react-router-dom";
import * as pdfjsLib from "pdfjs-dist";
import workerSrc from "pdfjs-dist/build/pdf.worker.min?url";
import "./Resume.css";

pdfjsLib.GlobalWorkerOptions.workerSrc = workerSrc;

function Resume() {
  const navigate = useNavigate();

  const [file, setFile] = useState(null);
  const [score, setScore] = useState(0);

  const [matched, setMatched] = useState([]);
  const [missing, setMissing] = useState([]);

  const [suggestion, setSuggestion] = useState("");

  const [loading, setLoading] = useState(false);
  const [popup, setPopup] = useState("");

  const showPopup = (msg) => {
    setPopup(msg);
    setTimeout(() => setPopup(""), 2500);
  };

  /* DOWNLOAD ROADMAP */

  const downloadRoadmap = () => {
    if (!missing.length) {
      showPopup("No improvement roadmap needed.");
      return;
    }

    const content = `Skill Improvement Roadmap

To improve your internship chances learn:

${missing.join("\n")}

Resources:
YouTube: https://www.youtube.com
Coursera: https://www.coursera.org
FreeCodeCamp: https://www.freecodecamp.org
Udemy: https://www.udemy.com

Generated by InternScan
`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = "Skill_Roadmap.txt";
    link.click();
  };

  /* ANALYZE RESUME */

  const analyzeResume = async () => {
    if (!file || file.type !== "application/pdf") {
      showPopup("Please upload a valid PDF resume");
      return;
    }

    setLoading(true);

    try {
      const arrayBuffer = await file.arrayBuffer();
      const pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;

      let text = "";

      for (let i = 1; i <= pdf.numPages; i++) {
        const page = await pdf.getPage(i);
        const content = await page.getTextContent();

        content.items.forEach((item) => {
          text += item.str + " ";
        });
      }

      text = text.toLowerCase();

      let internshipDesc = localStorage.getItem("internshipDesc") || "";

      if (!internshipDesc) {
        showPopup("No internship description found");
        setLoading(false);
        return;
      }

      internshipDesc = internshipDesc.toLowerCase();

      /* ROLE DETECTION */

      let role = "general";

      if (internshipDesc.includes("data analyst")) role = "data analyst";
      else if (internshipDesc.includes("data scientist"))
        role = "data scientist";
      else if (
        internshipDesc.includes("web") ||
        internshipDesc.includes("frontend") ||
        internshipDesc.includes("backend") ||
        internshipDesc.includes("full stack") ||
        internshipDesc.includes("Full-stack")
      )
        role = "web developer";
      else if (internshipDesc.includes("python")) role = "python developer";
      else if (internshipDesc.includes("machine learning"))
        role = "machine learning";
      else if (
        internshipDesc.includes("ui") ||
        internshipDesc.includes("ux") ||
        internshipDesc.includes("designer")
      )
        role = "ui/ux designer";
      else if (
        internshipDesc.includes("software") ||
        internshipDesc.includes("developer")
      )
        role = "software developer";
      else if (
        internshipDesc.includes("cybersecurity") ||
        internshipDesc.includes("security")
      )
        role = "cybersecurity analyst";
      else if (
        internshipDesc.includes("test engineer") ||
        internshipDesc.includes("testing")
      )
        role = "test engineer";

      /* SKILL DATABASE */

      const roleSkills = {
        "data analyst": [
          "excel",
          "sql",
          "power bi",
          "tableau",
          "python",
          "data visualization",
        ],

        "data scientist": [
          "python",
          "machine learning",
          "pandas",
          "numpy",
          "statistics",
          "tensorflow",
        ],

        "web developer": [
          "html",
          "css",
          "javascript",
          "react",
          "node",
          "database",
        ],

        "python developer": ["python", "django", "flask", "sql", "api"],

        "full stack developer": [
          "html",
          "css",
          "javascript",
          "react",
          "node",
          "express",
          "sql",
        ],

        "ui/ux designer": [
          "figma",
          "adobe",
          "user research",
          "design principles",
        ],

        "software developer": [
          "java",
          "python",
          "c++",
          "dsa",
          "git",
          "problem solving",
        ],

        "machine learning": ["python", "deep learning", "data processing"],

        "cybersecurity analyst": [
          "network security",
          "ethical hacking",
          "cryptography",
          "risk analysis",
        ],

        "test engineer": [
          "manual testing",
          "automation testing",
          "test case writing",
          "software testing life cycle",
        ],
      };

      let requiredSkills = roleSkills[role];

      if (!requiredSkills) {
        showPopup("Could not detect role from internship description");
        setLoading(false);
        return;
      }

      let matchedSkills = [];
      let missingSkills = [];

      requiredSkills.forEach((skill) => {
        if (text.includes(skill) || text.includes(skill.replace(" ", ""))) {
          matchedSkills.push(skill);
        } else {
          missingSkills.push(skill);
        }
      });

      let matchScore = Math.round(
        (matchedSkills.length / requiredSkills.length) * 100,
      );

      setScore(matchScore);
      setMatched(matchedSkills);
      setMissing(missingSkills);

      /* ✅ FIXED SUGGESTION LOGIC */

      if (requiredSkills.length === 0) {
        setSuggestion("Unable to analyze skills properly.");
      } else if (missingSkills.length === 0 && matchedSkills.length > 0) {
        setSuggestion(
          "Excellent! Your resume matches the internship requirements.",
        );
      } else {
        setSuggestion(
          "To improve your chances learn: " + missingSkills.join(", "),
        );
      }
    } catch (error) {
      console.error(error);
      showPopup("Error analyzing resume");
    }

    setLoading(false);
  };

  return (
    <div className="resume-page">
      <header>
        <div className="back-btn" onClick={() => navigate("/dashboard")}>
          ←
        </div>
      </header>

      {popup && <div className="popup">{popup}</div>}

      <div className="container">
        <div className="description">
          <h2>Resume Skill Analyzer</h2>
          <p>
            Upload your resume and InternScan will compare your skills with the
            internship requirements.
          </p>
        </div>

        <div className="card">
          <h3>Upload Resume</h3>

          <input
            type="file"
            accept=".pdf"
            onChange={(e) => setFile(e.target.files[0])}
          />

          <button onClick={analyzeResume} disabled={loading}>
            {loading ? "Analyzing Resume..." : "Analyze Resume"}
          </button>

          <div className="meter-box">
            <p>Resume Match Score</p>

            <div className="circle-meter">
              <div
                className="circle-progress"
                style={{
                  background: `conic-gradient(#2a5298 ${
                    score * 3.6
                  }deg,#ddd 0deg)`,
                }}
              >
                <div className="circle-inner">
                  <span>{score}%</span>
                </div>
              </div>
            </div>
          </div>

          <div className="skills-section">
            <div className="skills matched">
              <h4>Matched Skills</h4>

              {matched.length ? (
                matched.map((s, i) => <span key={i}>{s}</span>)
              ) : (
                <p>No matched skills</p>
              )}
            </div>

            <div className="skills missing">
              <h4>Missing Skills</h4>

              {missing.length ? (
                missing.map((s, i) => <span key={i}>{s}</span>)
              ) : (
                <p>No missing skills</p>
              )}
            </div>
          </div>

          <p className="suggestion">{suggestion}</p>

          <button onClick={downloadRoadmap}>
            Download Skill Improvement Roadmap
          </button>
        </div>
      </div>
    </div>
  );
}

export default Resume;
